CREATE OR REPLACE TABLE "CITIBIKE" (
    "RIDE_ID" VARCHAR(45),
    "RIDEABLE_TYPE" VARCHAR(45),
    "STARTED_AT" TIMESTAMP,
    "ENDED_AT" TIMESTAMP,
    "DURATION" FLOAT,
    "START_REGION" INT,
    "START_STATION_NAME" VARCHAR(45),
    "START_STATION_ID" VARCHAR(45),
    "END_REGION" INT,
    "END_STATION_NAME" VARCHAR(45),
    "END_STATION_ID" VARCHAR(45),
    "START_LAT" FLOAT,
    "START_LNG" FLOAT,
    "END_LAT" FLOAT,
    "END_LNG" FLOAT,
    "MEMBER_CASUAL" VARCHAR(45)
);

CREATE OR REPLACE TABLE "ZONE" (
    "LOCATIONID" INT,
    "ZONE" VARCHAR(45)
);

CREATE OR REPLACE TABLE "WEATHER" (
    "WEATHER_ID" INT AUTOINCREMENT,
    "W_DATE" DATE,
    "AWND" FLOAT,
    "PRCP" FLOAT,
    "TAVG" FLOAT
);

CREATE OR REPLACE TABLE "YELLOW_TAXI" (
    "YELLOWTAXI_TRIP_ID" INT AUTOINCREMENT,
    "VENDORID" INT,
    "TPEP_PICKUP_DATETIME" TIMESTAMP,
    "TPEP_DROPOFF_DATETIME" TIMESTAMP,
    "DURATION" FLOAT,
    "PASSENGER_COUNT" FLOAT,
    "TRIP_DISTANCE" FLOAT,
    "RATECODEID" FLOAT,
    "STORE_AND_FWD_FLAG" VARCHAR(45),
    "PULOCATIONID" INT,
    "DOLOCATIONID" INT,
    "PAYMENT_TYPE" INT,
    "FARE_AMOUNT" FLOAT,
    "EXTRA" FLOAT,
    "MTA_TAX" FLOAT,
    "TIP_AMOUNT" FLOAT,
    "TOLLS_AMOUNT" FLOAT,
    "IMPROVEMENT_SURCHARGE" FLOAT,
    "TOTAL_AMOUNT" FLOAT,
    "CONGESTION_SURCHARGE" FLOAT,
    "AIRPORT_FEE" FLOAT
);